Do not create venv during make dist on Travis CI
Builds on Travis CI already occur under a virtual Python environment.
For example, the virtual Python environment for Python 3.9 is located at
`/home/travis/virtualenv/python3.9.1` on Travis CI virtual machine.

Prior to this change, `make dist` depends on the `venv` target that
creates another virtual Python environment at
`/home/travis/.venv/mintotp` to create the distribution. However, the
build dependencies were installed earlier at
`/home/travis/virtualenv/python3.9.1`, not at
`/home/travis/.venv/mintotp` because the latter is not supposed to be
created during a Travis CI build. It is meant for local builds only. As
a result, the following occurs during `make dist`:

        error: invalid command 'bdist_wheel'
        Makefile:74: recipe for target 'dist' failed

This change fixes this issue by removing `venv` as a dependency of the
`dist` target.